EXPECTED_PAYMENT_DAY_MINIMUM = 1
# Based on the shortest month (February) minus 1
EXPECTED_PAYMENT_DAY_MAXIMUM = 27
EXPECTED_PAYMENT_AMOUNT_MINIMUM = 1

TIME_BONUS_AFTER_DUE_DATE_MULTIPLIER = 0.01
SCORE_MULTIPLIER = 0.01
TIME_BONUS_MULTIPLIER = 0.01
PREVIOUS_PAYMENTS_BONUS_MULTIPLIER = 0.3
