EXPECTED_PAYMENT_DAY_MINIMUM = 1
# Based on February - minimum number of days in a month
EXPECTED_PAYMENT_DAY_MAXIMUM = 28
EXPECTED_PAYMENT_AMOUNT_MINIMUM = 1

TIME_BONUS_AFTER_DUE_DATE_COEFFICIENT = 0.01
SCORE_COEFFICIENT = 0.01
TIME_BONUS_COEFFICIENT = 0.05
PREVIOUS_PAYMENTS_BONUS_COEFFICIENT = 0.3
